/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

//ans:4613732
import java.io.*;
import java.util.*;
public class Q2 {

	public static void main(String[] args) {
	            long n = 4000000,t1=1,t2=2,t3=0,sum=2;
	            while(t3<n)
	            {
	                if(t3%2==0)
	                {
	                    sum=sum+t3;
	                }
	                t3=t1+t2;
	                t1=t2;
	                t2=t3;
	               // System.out.println(t3);
	            }
	            System.out.println(sum);
	    }
}
